### ISSUE TITLE
Error: Status code 410

### ISSUE THREAD

**Issue by Th3Us3r** [ytmous/ytmous#15] opened 2022-01-15 05:43 UTC
Sometimes (randomly), when I click on a video, it just says `ytdl Error` then `Error: Status code: 410`. Is there anything causing this?

> here's how it looks:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/79815764/149610592-5b16c27e-ae8c-4219-bfea-9363f66bedc0.png">

**Comment by Yonle** [comment] 2022-01-15 05:46
This can be caused by ytdl issue, nor being ratelimited by youtube. You may do this step:

## If you host your own ytmous server
- Update ytdl
- Use proxy / VPN

## If you're using some mirrors
- Change to other mirror
- Consult to the mirror owner

**Comment by iop3** [comment] 2022-05-22 16:24
stale ?

**Comment by Yonle** [comment] 2022-05-22 23:15
> stale ?

Nope, as it's somewhat applies to ytdl itself.

**Comment by iop3** [comment] 2022-05-22 23:27
lol ok

**Comment by Yonle** [comment] 2023-01-07 01:24
Mirror specific. Closing

**Closed by Yonle** 2023-01-07 01:24 UTC
